name: voynich_example
description: Demonstrates how to use the voynich plugin.
publish_to: 'none'

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  voynich:
    path: ../

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.10.0

flutter:
  uses-material-design: true
