include: package:lint/analysis_options.yaml

linter:
  rules:
    always_use_package_imports: false
    sort_pub_dependencies: false
    prefer_int_literals: true
    unnecessary_lambdas: true
    avoid_slow_async_io: true
    unawaited_futures: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/*"