name: voynich
description: A native cryptography plugin.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.10.0

flutter:

  plugin:
    platforms:
      android:
        package: tabsvsspaces.voynich
        pluginClass: VoynichPlugin
      ios:
        pluginClass: VoynichPlugin